development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: online_test_development
  pool: 5
  username: root
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: online_test_developments
  pool: 5
  username: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gkmit_production
  pool: 5
  username: root
  host: localhost